export const SW_LOGIN_SUCCESS = 'SW_USERS_LOGIN_SUCCESS';
export const SW_LOGIN_ERROR = 'SW_USERS_LOGIN_ERROR';
export const LOGOUT = 'USERS_LOGOUT';
export const SW_SIGNUP_SUCCESS = 'SW_USERS_SIGNUP_SUCCESS';
export const SW_SIGNUP_ERROR = 'SW_USERS_SIGNUP_ERROR';
export const USER_DETAILS_SUCCESS = 'SW_USER_DETAILS_SUCCESS';
export const USER_DETAILS_ERROR = 'SW_USER_DETAILS_ERROR';
